DatabaseConfig:
  host:
  port:
  username:
  password:
  database:
  ssl: true
  customHttpParams: async_insert=1, wait_for_async_insert=1
  socketTimeout: 300000
  socketKeepAlive: true
  connectTimeout: 5000

TickersDataConfig:
  TickersDataUploaderConfig:
    maxFlushDataAttempts: 3
    divideDataPartsQuantity: 32
    tickersDataPath:
    sleepOnReconnectMs: 500

  CompressionHandlerConfig:
    compressionBufferSize: 131072

MainFlowsConfig:
  DiscoverNewFilesConfig:
    filesBufferSize: 8192
    flushDiscoveredFilesTimeoutSec: 15 # almost the same as work_cycle_time_sec
    sleepOnReconnectMs: 3000
    maxReconnectAttempts: 3

  ProceedFilesStatusConfig:
    workCycleTimeSec: 20
    sleepOnReconnectMs: 3000
    maxReconnectAttempts: 3

  UploadTickersDataConfig:
    workCycleTimeSec: 30
    sleepOnReconnectMs: 3000
    maxReconnectAttempts: 3

  CleanupUploadedFilesConfig:
    workCycleTimeHours: 3
    sleepOnReconnectMs: 3000
    maxReconnectAttempts: 3
